// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	Sk         uint64
	Pid        uint32
	LocalIp4   uint32
	RemoteIp4  uint32
	LocalPort  uint16
	RemotePort uint16
	Op         uint8
	Pname      [16]uint8
	_          [7]byte
}

type BpfGlobal struct {
	_   structs.HostLayout
	Cnt uint64
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	FexitSysAccept     *ebpf.ProgramSpec `ebpf:"fexit_sys_accept"`
	FexitSysAccept4    *ebpf.ProgramSpec `ebpf:"fexit_sys_accept4"`
	SockopsTcpLifetime *ebpf.ProgramSpec `ebpf:"sockops_tcp_lifetime"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	Globals        *ebpf.MapSpec `ebpf:"globals"`
	SockmapSockets *ebpf.MapSpec `ebpf:"sockmap_sockets"`
	TcpSockets     *ebpf.MapSpec `ebpf:"tcp_sockets"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	Unused1        *ebpf.VariableSpec `ebpf:"_unused1"`
	UnusedTaskInfo *ebpf.VariableSpec `ebpf:"_unused_task_info"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	Globals        *ebpf.Map `ebpf:"globals"`
	SockmapSockets *ebpf.Map `ebpf:"sockmap_sockets"`
	TcpSockets     *ebpf.Map `ebpf:"tcp_sockets"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Globals,
		m.SockmapSockets,
		m.TcpSockets,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	Unused1        *ebpf.Variable `ebpf:"_unused1"`
	UnusedTaskInfo *ebpf.Variable `ebpf:"_unused_task_info"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	FexitSysAccept     *ebpf.Program `ebpf:"fexit_sys_accept"`
	FexitSysAccept4    *ebpf.Program `ebpf:"fexit_sys_accept4"`
	SockopsTcpLifetime *ebpf.Program `ebpf:"sockops_tcp_lifetime"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.FexitSysAccept,
		p.FexitSysAccept4,
		p.SockopsTcpLifetime,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
